### ISSUE TITLE
Improve handling of the exception that are generated when a blob has been deleted

### ISSUE THREAD

**Issue by SandGrainOne** [Altinn/altinn-file-scan#100] opened 2023-09-19 13:17 UTC
### Description

Blobs being deleted before we start a file scan occasionally results in Internal Server Error in the file scan application.

In this specific case the file scan application should return Ok instead. The situation should still be logged, but the log level should be Warning instead of Error.

### Additional Information

This should be improved to avoid unnecessary alerts. There are currently an alert rule if the file scan application responds to requests with Internal Server Error.

**Comment by acn-sbuad** [comment] 2024-02-28 08:38
duplicate of #43. Closing

**Closed by acn-sbuad** 2024-02-28 08:38 UTC
Labels: kind/user-story, status/draft
